const CardData = [
    {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#23af52',
        name: 'Vinay Kumar',
        heading: 'Learn WEBDEVELOPMENT WITH ME',
        firstbutton: '6 Tasks',
        secondbutton: '30 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: ' #5038b0',
        name: 'Anjali Singh',
        heading: 'Master PYTHON PROGRAMMING',
        firstbutton: '8 Tasks',
        secondbutton: '40 XPs',
        thirdbutton: '1 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#bb5e35',
        name: 'Rohan Sharma',
        heading: 'Introduction to DATA SCIENCE',
        firstbutton: '5 Tasks',
        secondbutton: '25 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#bb3fda',
        name: 'Priya Rao',
        heading: 'Learn REACT NATIVE',
        firstbutton: '10 Tasks',
        secondbutton: '50 XPs',
        thirdbutton: '2 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#23af52',
        name: 'Amit Verma',
        heading: 'Deep Dive into MACHINE LEARNING',
        firstbutton: '7 Tasks',
        secondbutton: '35 XPs',
        thirdbutton: '1 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: ' #5038b0',
        name: 'Sonal Patel',
        heading: 'JAVA for Beginners',
        firstbutton: '6 Tasks',
        secondbutton: '30 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#bb5e35',
        name: 'Karan Johar',
        heading: 'ANDROID Development Basics',
        firstbutton: '8 Tasks',
        secondbutton: '40 XPs',
        thirdbutton: '1 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#bb3fda',
        name: 'Neha Gupta',
        heading: 'CSS Mastery',
        firstbutton: '5 Tasks',
        secondbutton: '25 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#af33ff',
        name: 'Ravi Kumar',
        heading: 'Understanding NODE.JS',
        firstbutton: '10 Tasks',
        secondbutton: '50 XPs',
        thirdbutton: '2 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#33ff57',
        name: 'Divya Narang',
        heading: 'Learn HTML5',
        firstbutton: '6 Tasks',
        secondbutton: '30 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#3375ff',
        name: 'Pankaj Mehta',
        heading: 'Get Started with RUBY',
        firstbutton: '7 Tasks',
        secondbutton: '35 XPs',
        thirdbutton: '1 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#ff33a1',
        name: 'Anil Kapoor',
        heading: 'FLUTTER Development',
        firstbutton: '8 Tasks',
        secondbutton: '40 XPs',
        thirdbutton: '1 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#33afff',
        name: 'Sana Khan',
        heading: 'Advanced SQL Techniques',
        firstbutton: '5 Tasks',
        secondbutton: '25 XPs',
        thirdbutton: '0 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#6e6e6e',
        name: 'Manoj Desai',
        heading: 'Learn PHP Programming',
        firstbutton: '10 Tasks',
        secondbutton: '50 XPs',
        thirdbutton: '2 official',
      },
      {
        image: 'https://via.placeholder.com/300x150',
        backgroundColor: '#af33a1',
        name: 'Manoj Desai',
        heading: 'Learn PHP Programming',
        firstbutton: '10 Tasks',
        secondbutton: '50 XPs',
        thirdbutton: '2 official',
      }
  ];
  
  export default CardData;
  